### ISSUE TITLE
Cookie only set on page refresh

### ISSUE THREAD

**Issue by lam0r86** [michnhokn/kirby3-cookie-banner#13]
Hello,

got a problem. When cookies are accepted all or saved once, the code won´t start directly. I have to refresh the page, that the cookie is loaded. Are there any options to make a page refresh after accepting cookies?

BR
Matthias

**Comment by michnhokn** [comment]
Hey Matthias,

have a look at: [the wiki](https://github.com/michnhokn/kirby3-cookie-banner/wiki/01-How-to-set-it-up#-intercept-changes-to-the-cookie-settings)
You can easyly replace the `console.log()` in the example with something like: `location.reload();`.

I hope that helps you.

**Comment by lam0r86** [comment]
@michnhokn Thanks at all, but where do I change it? Sorry but I am not an really expert by this, but Iam familiar with php. If you can tell me where, then it would be easy for me :)

**Comment by michnhokn** [comment]
Hey @lam0r86,

No problem with pleasure.
Best before the `footer` tag. Accordingly in the `footer.php`.
There then simply wrap with a script tag:
```
<script> ... </script>
```

I hope this helps.

**Comment by lam0r86** [comment]
Thanks to you @michnhokn yesterday i found Helpful script at getkirby. Now it is okay 😉 thanks

**Comment by lam0r86** [comment]
Hey @michnhokn 

How to add Cookie stuft to essentiell? 

<?php if (isFeatureAllowed('analytics')): ?>

br 
Matthias

**Comment by michnhokn** [comment]
Hey @lam0r86

What excatly do you mean? You define what the essential cookies "contain" by yourself.
There is no more features then saving the consent from the users in this plugin.
