### ISSUE TITLE
EN and DE translations are supplied by default but DE does not work automatically

### ISSUE THREAD

**Issue by squareclouds** [michnhokn/kirby3-cookie-banner#16]
hello,

i am using kirby 3.6.0. if i understood correctly the plugin ships with the texts for EN and DE. if i switch languages in the frontend the text does not translate, though. only after implementing the translation myself (via languages/de.php) the modal shows the translated content. any idea why this is happening?

**Comment by fsennj** [comment]
HI - i have more or less the same problem. only that my default (DE) page is in en, and the en is in de.

the dE language is just xxx.at/   and the en language is xxx.at/en

any clud how to fix?

i tried in  index.php to change the values like this:

 ],
    'translations' => [
        'de' => [
            'michnhokn.cookie-banner' => DEFAULT_CONTENT
        ],
        'en' => [
            'michnhokn.cookie-banner.title' => 'Cookie settings',
            'michnhokn.cookie-banner.text' => 'We use cookies to provide you with the best possible experience. They also allow us to analyze user behavior in order to constantly improve the website for you. (link: en/gdpr text: Privacy Policy)',
            'michnhokn.cookie-banner.essentialText' => 'Essential',
            'michnhokn.cookie-banner.denyAll' => 'Reject All',
            'michnhokn.cookie-banner.acceptAll' => 'Accept All',
            'michnhokn.cookie-banner.save' => 'Save settings',
        ]

but not working. 

thank you

**Comment by christianschley** [comment]
https://github.com/michnhokn/kirby3-cookie-banner/pull/17

I found the error and created a pull request
