### ISSUE TITLE
Cookie is not set (nginx)

### ISSUE THREAD

**Issue by andreasotto** [michnhokn/kirby3-cookie-banner#3]
The cookie is not set.

Environment: nginx (valet+ on macOS)

The modal appears on every page load. No cookies in the browser inspector. To reproduce setup a kirby installation for example plainkit on nginx (valet+), and follow your instructions (include the snippet line just before the closing body tag). The modal dialog appears, but the cookie will not be set when clicked Accept all.

**Comment by marcschneider123** [comment]
The cookie is set with the secure option in cookie-modal.js

```js
Cookies.set(
  'cookie_status',
  features.join(','),
  {expires: 365, secure: true},
  );
```

So the cookie is not set on http sites. I did `valet secure sitename` and then it worked after visiting the site via https://.

**Comment by michnhokn** [comment]
@marcschneider123 Thank you for the response. 
I think it should be standard, because a HTTP web should not really exist anymore. However, it would be good to disable this option for the local (mostly insecure) environment.

**Comment by michnhokn** [comment]
@andreasotto Have a look at the new release [1.0.6](https://github.com/michnhokn/kirby3-cookie-banner/releases/tag/1.0.6)
