### ISSUE TITLE
cookie banner only by call

### ISSUE THREAD

**Issue by fritzlaszlo** [michnhokn/kirby3-cookie-banner#5]
Heya,
thanks for the fantastic plugin! It's a lifesaver!

I realized on many smaller website projects I don't use cookies at all. The only recurring exceptions are not-so-privacy-confirm embeds from various platforms. So inspired by githubs removal of the cookie banner (https://github.blog/2020-12-17-no-cookie-for-you/) I was wandering:

**Is there a way to prevent the banner plugin from popping up at all until you actually call it via a button?**
Maybe another variable could be introduced, that is by default true, so the regular behavior doesn't change. And only when false, it prevents the cookie modal snippet from automatically popping up, but keeps button+js call possibility.

This way the banner could be kept away from visitors until they actually stumble on some third-party content on one of the subpages, where an overlay asks them to confirm the loading process (aka triggers the cookie banner and then the rest).

**Comment by michnhokn** [comment]
Hey @fritzlaszlo that is an excellent idea. I will implement it as soon as possible. Thanks for the input.

**Comment by michnhokn** [comment]
[Release 1.0.8](https://github.com/michnhokn/kirby3-cookie-banner/releases/tag/1.0.8)
